### ISSUE TITLE
Trouble after build

### ISSUE THREAD

**Issue by Ygarr** [MCLx86/xtreemtest#1]
While build got such
```
-- Found IrrlichtMt 1.9.0.9
CMake Error at CMakeLists.txt:135 (message):
  IrrlichtMt 1.9.0mt8 is required to build
```
After fixing 1.9.0mt8 to 1.9.0.9 built successfully but got as in attach:
![Screenshot from 2022-11-19 15-47-57](https://user-images.githubusercontent.com/14309871/202853889-168e93e1-3bfb-4df0-91dc-114276cdd28d.png)

**Comment by MCLx86** [comment]
Thank you for reporting this issue.  
XtreemTest is currently in testing and not suitable for daily use.
This is a known issue.
We appreciate your interest in the project.
